---
- name: Install and start Apache
  hosts: all
  become: yes
  gather_facts: False
  tasks:
    - name Install Apache
      apt:
      - name: apache2
        state: latest
        
    - name Start Service
      service:
        name: apache2
        enabled: yes
        state: started